### PR TITLE
Adding elif for Pico

### PR DESCRIPTION
**Pull request by BlitzCityDIY**
Adding elif in examples for Pico to match the pinouts on the PiCowbell

### CODE REVIEW

**Comment by caternuson** [comment]
Would these same pins work for a Pico W?

**Comment by BlitzCityDIY** [comment]
@caternuson ah good point, i'll add the W as well since the pins are for the MCP2515 on the PiCowbell.

**Comment by caternuson** [comment]
This looks like some cleanup I forgot to delete in the previous PR :(

Can you delete all these lines from the `MCP2515_CAN_ReceiverCallback.ino` example:
```cpp
//
// Comment/uncomment interrupt (INT) pin for Feather used
//
// Feather M0, M4, ESP32-S2, ESP32-S3
#define INT_PIN (6)
// Feather RP2040
// #define INT_PIN (8)
// Feather ESP32 V1 and V2
// #define INT_PIN (32)
// Feather ESP8266
// #define INT_PIN (16)
```

That was the original setup before replacing with the if/elif logic. The `INT_PIN` is now defined there.

**Comment by BlitzCityDIY** [comment]
@caternuson sure! no problem

**Comment by caternuson** [comment]
Thanks! LGTM. Gonnna merge and release and stuff.

**Review by caternuson — APPROVED** [review]

**Pull request merged**
